CREATE TABLE MARCAS(
	ID_MARCAS INT NOT NULL PRIMARY KEY,
	NOMBRE_MARCAS VARCHAR(100)
);

CREATE TABLE MODELOS(
	ID_MODELOS INT PRIMARY KEY,
	NOMBRE_MODELOS VARCHAR(100)
);

ALTER TABLE MARCAS
MODIFY ID_MARCAS INT NOT NULL AUTO_INCREMENT;

ALTER TABLE MODELOS
MODIFY ID_MODELOS INT NOT NULL AUTO_INCREMENT;

CREATE TABLE TELEFONOS(
	ID_TELEFONO INT NOT NULL PRIMARY KEY,
	IMEI VARCHAR(50),
	MODELO INT NOT NULL,
	MARCA INT NOT NULL,
	MAC_ADRESS VARCHAR(64),
	FOREIGN KEY (MODELO) REFERENCES MODELOS(ID_MODELOS),
	FOREIGN KEY (MARCA) REFERENCES MARCAS(ID_MARCAS)
); 

ALTER TABLE TELEFONOS
MODIFY ID_TELEFONO INT NOT NULL AUTO_INCREMENT;
